import {useEffect,useState} from 'react';
import {ChartNoAxesCombined,ShieldCheck,LoaderCircle} from 'lucide-react';
import Admin from './admin';
import FinPredict from '../app/finpredict';
import {LanguagePicker} from '../components/language-picker';
import {tr,useLanguage} from '../lib/i18n';
import {api} from '../lib/api';
type User={id:string;name:string;email:string;role?:string};
type AuthResponse={user:User|null;csrfToken:string};
export default function AuthRoot(){
 useLanguage();
 const [user,setUser]=useState<User|null>(null),[loading,setLoading]=useState(true),[mode,setMode]=useState<'login'|'register'>('login'),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [name,setName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState('');
 const load=()=>{setLoading(true);setError('');api<AuthResponse>('/api/auth/me').then(d=>setUser(d.user)).catch(e=>setError(e.message)).finally(()=>setLoading(false));};
 useEffect(()=>{load();const expire=()=>{setUser(null);setPassword('');load();};window.addEventListener('finpredict-session-expired',expire);return()=>window.removeEventListener('finpredict-session-expired',expire);},[]);
 async function submit(e:React.FormEvent){e.preventDefault();setError('');if(mode==='register'&&password!==confirm){setError('Пароли не совпадают');return;}setBusy(true);try{const d=await api<AuthResponse>('/api/auth/'+mode,{method:'POST',body:JSON.stringify({name,email,password})});setUser(d.user);setPassword('');setConfirm('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function logout(){try{await api('/api/auth/logout',{method:'POST',body:'{}'});setUser(null);setPassword('');setConfirm('');setError('');}catch(e){setError((e as Error).message);}}
 if(loading)return <div className="auth-loading"><LoaderCircle className="spin" size={30}/><p>{tr('Загрузка…')}</p></div>;
 if(user)return <>{user.role==='admin'?<Admin user={user} onLogout={logout}/>:<FinPredict key={user.id} user={user} onLogout={logout}/>}{error&&<div className="auth-global-error" role="alert">{tr(error)}<button onClick={()=>setError('')}>×</button></div>}</>;
 return <main className="auth-page"><aside className="auth-story"><div className="auth-logo"><ChartNoAxesCombined size={30}/><span>FinPredict <b>AI</b></span></div><div><span className="tiny-label">FINPREDICT AI</span><h1>{tr('ВАШИ ФИНАНСЫ ПОД КОНТРОЛЕМ')}</h1><p>{tr('Всё о ваших деньгах — в одном месте.')}</p><div className="auth-features"><span>{tr('Текущий баланс')}</span><span>{tr('Аналитика')}</span><span>{tr('Прогноз расходов')}</span></div></div><p className="auth-security"><ShieldCheck size={20}/>{tr('Пароли защищены. У каждого аккаунта своя история операций.')}</p></aside><section className="auth-form-area"><div className="auth-language"><LanguagePicker/></div><div className="auth-card"><div className="auth-tabs"><button type="button" className={mode==='login'?'active':''} onClick={()=>{setMode('login');setError('');setPassword('');setConfirm('');}}>{tr('Вход')}</button><button type="button" className={mode==='register'?'active':''} onClick={()=>{setMode('register');setError('');setPassword('');setConfirm('');}}>{tr('Регистрация')}</button></div><h2>{tr(mode==='login'?'Добро пожаловать':'Начните управлять финансами')}</h2><p>{tr(mode==='login'?'Войдите, чтобы открыть свой баланс, операции и прогноз.':'Создайте личный кабинет. Баланс и история начнутся с нуля.')}</p><form className="operation-form" onSubmit={submit}>{mode==='register'&&<label>{tr('Имя')}<input autoComplete="name" value={name} onChange={e=>setName(e.target.value)} required maxLength={120}/></label>}<label>Email<input type="email" autoComplete="username" required value={email} onChange={e=>setEmail(e.target.value)} maxLength={254}/></label><label>{tr('Пароль')}<input type="password" autoComplete={mode==='login'?'current-password':'new-password'} required minLength={mode==='register'?8:1} maxLength={128} value={password} onChange={e=>setPassword(e.target.value)} placeholder={mode==='register'?tr('Не менее 8 символов'):''}/></label>{mode==='register'&&<label>{tr('Повторите пароль')}<input type="password" autoComplete="new-password" required minLength={8} maxLength={128} value={confirm} onChange={e=>setConfirm(e.target.value)}/></label>}{error&&<p role="alert" className="inline-error">{tr(error)}</p>}<button type="submit" className="primary-btn full-width" disabled={busy}>{busy&&<LoaderCircle className="spin" size={16}/>} {tr(mode==='login'?'Войти':'Создать аккаунт')}</button></form>{error&&<button className="text-btn auth-retry" onClick={load}>{tr('Попробовать снова')}</button>}<small className="auth-footnote">{tr('Данные демонстрационные · банковское подключение не требуется')}</small></div></section></main>;
}
